blog/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('tag/<slug:slug>/', TagListView.as_view(), name='tag_view'),
    path('<slug:category>/<slug:slug>/', PostDetail.as_view(), name='post_detail'),
    path('<slug:category>/', PostCategory.as_view(), name='post_list_category'),
    path('', PostCategory.as_view()),
]

cms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
    path('feedback/', include('feedback.urls')),
    path('shop/', include('apps.shop.urls')),
    path('search/', include('apps.search.urls')),
    path('blog/', include('blog.urls')),
    path('', include('pages.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from mptt.models import MPTTModel, TreeForeignKey


class Category(MPTTModel):
    """Модель категорий статей"""
    name = models.CharField("Название", max_length=150)
    slug = models.SlugField("url", max_length=160)
    active = models.BooleanField("Опубликовать", default=True)
    parent = TreeForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='children')
    template = models.CharField("Шаблон", max_length=500, default="blog/post-list.html")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("post_list_category", kwargs={"category": self.slug})

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Tag(models.Model):
    """Модель тегов к статье"""
    name = models.CharField("Название", max_length=50)
    slug = models.SlugField("url", max_length=60)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tag_view', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"


class Post(models.Model):
    """Модель статей"""
    title = models.CharField("Заголовок", max_length=150)
    sub_title = models.CharField("Под заголовок", max_length=150)
    mini_text = models.TextField("Превью статьи", max_length=500)
    text = models.TextField("Статья")
    created = models.DateTimeField("Дата создания", auto_now_add=True)
    publish_date = models.DateTimeField("Дата публикации", default=timezone.now)
    active = models.BooleanField("Опубликовать", default=True)
    sort = models.PositiveIntegerField("Порядок", default=0, unique=True)
    view = models.PositiveIntegerField("Просмотры", default=0)
    tags = models.ManyToManyField(Tag, verbose_name="Теги")
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True)
    slug = models.SlugField("url", max_length=160, unique=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={"category": self.category.slug, "slug": self.slug})

    def comment_all(self):
        return Comment.objects.filter(post_id=self.id, moderated=True)

    class Meta:
        verbose_name = "Статья"
        verbose_name_plural = "Статьи"
        ordering = ["-created"]


class Comment(models.Model):
    """Модель комментариев к статье"""
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=models.CASCADE)
    message = models.TextField("Комментарий", max_length=1000)
    post = models.ForeignKey(Post, verbose_name="Статья", on_delete=models.CASCADE)
    created = models.DateTimeField("Дата", auto_now_add=True)
    moderated = models.BooleanField("Статус одбрено", default=False)

    def __str__(self):
        return self.message

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

blog/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    """Форма комментариев"""
    class Meta:
        model = Comment
        fields = ("message",)

blog/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.views import View
from django.views.generic import ListView, DetailView, CreateView


from .models import Post, Comment, Tag
from .forms import CommentForm


class PostCategory(ListView):
    """Вывод статей"""
    model = Post
    template_name = "blog/post-list.html"
    context_object_name = "post_list"

    def get_queryset(self):
        if self.kwargs.get("category") is not None:
            posts = Post.objects.filter(category__slug=self.kwargs.get("category"), category__active=True)
            if posts.exists():
                self.template_name = posts.first().category.template
            else:
                raise Http404
        else:
            posts = Post.objects.filter(category__active=True)
        if not posts.exists():
            raise Http404
        return posts


# class PostList(View):
#     """Вывод списка статей"""
#     def get(self, request, *args, **kwargs):
#         posts = Post.objects.filter(category__active=True)
#         return render(request, 'blog/post-list.html', {"post_list": posts})


# class PostCategory(View):
#     def get(self, request, category, *args, **kwargs):
#         posts = Post.objects.filter(category__slug=category, category__active=True)
#         if posts.exists():
#             return render(request, 'blog/post-list.html', {"post_list": posts})
#         else:
#             raise Http404


# class PostList(ListView):
#     """Вывод списка статей"""
#     model = Post
#     queryset = Post.objects.filter(category__active=True)
#     template_name = "blog/post-list.html"
#     context_object_name = "post_list"


class PostDetail(DetailView, CreateView):
    """Вывод полной статьи"""
    model = Post
    template_name = "blog/post-detail.html"
    context_object_name = "post"
    form_class = CommentForm
#   success_url = '/'

    def form_valid(self, form):
        form.instance.post = Post.objects.get(slug=self.kwargs.get('slug'))
        form.instance.user = self.request.user
        form.save()
        messages.add_message(self.request, settings.MY_INFO, "Ваш комментарий отправлен на проверку, спасибо")
#       self.success_url = reverse_lazy("post_detail", kwargs={"category": self.category.slug, "slug": self.slug})
        self.success_url = form.instance.post.get_absolute_url()
        return super().form_valid(form)


# class PostDetail(View):
#     """Вывод полной статьи"""
#     def get(self, request, category, slug):
#         post = get_object_or_404(Post, slug=slug)
#         form = CommentForm()
#         return render(request, "blog/post-detail.html", {'post': post, "form": form})
#
#     def post(self, request, category, slug):
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             form = form.save(commit=False)
#             form.post = Post.objects.get(slug=slug)
#             form.user = request.user
#             form.save()
#             messages.add_message(request, settings.MY_INFO, "Ваш комментарий отправлен на проверку, спасибо")
#         else:
#             messages.add_message(request, settings.MY_INFO, "Ошибка")
#             return redirect(request.path)


class TagListView(ListView):
    model = Post
    template_name = 'blog/tag-list.html'
    context_object_name = "tag"

    def get_queryset(self):
        return Tag.objects.get(slug=self.kwargs['slug'])

templates/blog/base.html
{% extends 'base.html' %}

{% block content %}
    <div class="main-blog">
        <div class="sidebar">
            {% block sidebar %}
            {% include 'blog/sidebar.html' %}
            {% endblock sidebar %}
        </div>
        <div class="content">
            {% block post %}
            {% endblock post %}
        </div>
    </div>
{% endblock content %}

templates/blog/post-detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block post %}
{% category_list publish='False' %}

    <h1>{{post.title}}</h1>
    <h2>{{post.description}}</h2>
    <p>{{post.text}}</p>
    <hr>
    <p>Просмотров: {{post.view}}</p>
    <p>Категория: <a href="{{ post.category.get_absolute_url }}">{{post.category}}</a></p>
    {% for tag in post.tags.all %}
    <p>Теги: <a href="{{ tag.get_absolute_url }}">{{ tag }}</a></p>
    {% endfor %}
    <p>Дата - {{ post.created|date:"D d M Y"  }}</p>
    <hr>
    {% if messages %}
        {% for message in messages %}
            <p style="color: peru;">{{ message }}</p>
        {% endfor %}
    {% endif %}
    {% if user.is_authenticated %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Отправить</button>
    </form>
    {% else %}
    <p>Что бы оставить комментарий <a href="/accounts/login/">войдите</a> на сайт или <a href="/accounts/signup/">зарегестрируйтесь</a></p>
    {% endif %}
    <h2>Всего комментариев: {{ post.comment_all.count }}</h2>
    {% for comment in post.comment_all %}
        {% if forloop.counter|comment_padding %}
            <p style="padding: 10px; border: 1px solid blue; margin-left: 50px;">
        {% else %}
            <p style="padding: 10px; border: 1px solid red;">
        {% endif %}
            {{ comment.user }}<br>
            {{ comment.message }}<br/>
            <small>{{ comment.created }}</small>
            </p>
    {% endfor %}

{% endblock post %}

templates/blog/post-list-test.html
{% extends 'blog/base.html' %}

{% block post %}
    <h1>Test</h1>
    {% for post in post_list %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {% endfor %}
{% endblock post %}

templates/blog/post-list.html
{% extends 'blog/base.html' %}

{% block post %}
    {% for post in post_list %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
    {% endfor %}
{% endblock post %}

templates/blog/sidebar.html
{% load blog_tags %}

{% category_list %}

templates/blog/tag-list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Тег - {{ tag.name }}</h1>
    <div class="container columns is-multiline">

        {% for post in tag.post_set.all %}
            <article class='column is-3 is-6-tablet'>
                <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
                <p>{{ post.sub_title }}</p>
                <div>
                    {{ post.preview }}
                </div>

            </article>
        {% endfor %}
    </div>
{% endblock content %}